#!/usr/bin/env bash

VERSION=1.0.0
PHP=php

function main {
    if [[ -f .env ]]; then
        source .env
    fi
    getPhp
    if [[ $# -gt 0 ]]; then
        case "$1" in
            pre-commit)
                phpCsFixer
                ;;
            pre-push)
                phpCsFixer --dry-run
                ;;
            update)
                cgHooks update
                ;;
            add)
                cgHooks add --ignore-lock
                ;;
            install)
                codeStyleFixer install
                ;;

            # Get version
            -v|--version)
                echo ${VERSION}
                ;;
        esac
    fi
}

function phpCsFixer {
    if [[ ! -f ./vendor/bin/php-cs-fixer ]]; then
        echo "php-cs-fixer bin not found in ./vendor/bin. Please use composer require --dev friendsofphp/php-cs-fixer"
        exit 0
    fi
    ${PHP} ./vendor/bin/php-cs-fixer fix "$@"
}

function cgHooks {
    if [[ ! -f ./vendor/bin/cghooks ]]; then
        echo "cghooks bin not found in ./vendor/bin. Please use composer require --dev brainmaestro/composer-git-hooks"
        exit 0
    fi
    ${PHP}  ./vendor/bin/cghooks "$@"
}

function codeStyleFixer {
    if [[ ! -f ./vendor/bin/code-style-fixer ]]; then
        echo "code-style-fixer bin not found in ./vendor/bin. Please use composer require --dev brackets/code-style-fixer"
        exit 0
    fi
    ${PHP}  ./vendor/bin/code-style-fixer "$@"
}

function getPhp {
    command -v docker >/dev/null 2>&1
    if [[ $? -eq 0 ]] && [[ ${GIT_HOOKS_IGNORE_DOCKER} != true ]] && [[ -f harbor ]]; then
            PSRESULT="$(docker-compose ps -q)"
            if [[ ! -z "$PSRESULT" ]]; then
                PHP="./harbor exec -T php"
            else
                PHP="./harbor run --rm php"
            fi
    fi
}

main "$@"
