#!/usr/bin/env php
<?php

$dir = getcwd();
if (is_file($autoload = __DIR__ . '/vendor/autoload.php')) {
    require_once $autoload;
} elseif (is_file($autoload = __DIR__ . '/../../autoload.php')) {
    require_once $autoload;
} else {
    fwrite(
        STDERR,
        'You must set up the project dependencies, run the following commands:' . PHP_EOL .
        'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    exit(1);
}

use Brackets\CodeStyleFixer\InstallCommand;
use Symfony\Component\Console\Application;

$application = new Application('Code Style Fixer', '1.0.0');

$application->add(new InstallCommand());

$application->run();
